---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
language: ruby
notifications:
  email:
  - ngiger@ywesee.com
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- jruby
# - ruby-head # excluded at the moment because it does not find a bundler version
# whitelist of branches to build
branches:
  only:
    - master
