language: ruby

bundler_args: --without debugger
script:
  - bundle exec rake rebuild
  - bundle exec rake install
  - bundle exec rake test

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.2.3  # order is different for some hashes


# Speed up things on travis by using new docker based infrastructure and caching bundler
sudo: false
cache: bundler